FORMAT: 1A
HOST: https://api.mydnshost.co.uk/1.0

# MyDNSHost API
This document describes the current API (Version 1.0) for MyDNSHost.

You can use this guide to learn how to interact with the API yourself, or you can
use one of the pre-written API libraries:

 - PHP: https://github.com/mydnshost/mydnshost-php-api (This is what the default frontend uses to interact with the api)
 - Python: https://github.com/mydnshost/mydnshost-python-api
 - Go: https://github.com/mydnshost/mydnshost-go-api
