# Group System
Endpoints for dealing with system internals.

Whilst every effort will be made to keep the API stable, resources available under this endpoint are subject to change without warning as required.

## System Information [/system/datavalue/{datavalue}]
### Get system datavalues from the API [GET]
This lets you get system datavalues from the api. These are mostly used by the frontend to allow it to dynamically adapt to certain backend changes.

Some datavalues require authentication, some do not.

+ Parameters

    + datavalue: `validPermissions` (required, string) - The datavalue to get.

+ Response 200 (application/json)
    + Body

            {
                "respid": "59b5f1440fca4",
                "method": "system/datavalue/validPermissions",
                "response":{
                    "validPermissions":[
                        "domains_stats",
                        "manage_domains",
                        "domains_create",
                        "manage_users",
                        "manage_permissions",
                        "impersonate_users"
                    ]
                }
            }


## System Statistics [/system/stats/{stat}{?type}]
### Get system statistics from the API [GET]
This lets you get system-level statistics from the api.

+ Parameters
    + stat: `queries-per-server` (required, string) - The statistic to get (queries-per-server, queries-per-rrtype, queries-per-zone).
    + type: `raw` (optional, string) - Type of stats (raw or derivative)

+ Response 200 (application/json)
    + Body

            {
                "respid": "59b5faf590931",
                "method": "system/stats/queries-per-server",
                "response":{
                    "stats":{
                        "ns1":[
                            {"time": 1505094900, "value": 18},
                            {"time": 1505094960, "value": 26},
                            {"time": 1505095020, "value": 28},
                            // More Stats
                            {"time": 1505098380, "value": 23},
                            {"time": 1505098440, "value": 8}
                        ],
                        // More Servers
                        "ns4":[
                            {"time": 1505094900, "value": 14},
                            {"time": 1505094960, "value": 18},
                            {"time": 1505095020, "value": 28},
                            // More Stats
                            {"time": 1505098380, "value": 28},
                            {"time": 1505098440, "value": 6}
                        ]
            }
