
# Group Experimental
There may be some experimental endpoints available under /experimental from time to time, these are mostly undocumented and should not be relied on.

You can find more information about some of these at <a href="https://api.mydnshost.co.uk/experimental/docs/">https://api.mydnshost.co.uk/experimental/docs/</a>
